### PR TITLE
complete Single customer view

### PR DESCRIPTION
**Pull request by KarenEfereyan**

### CODE REVIEW

**Comment by kofimokome** [comment]
@KarenEfereyan can you fix merge conflicts?
I may not merge now since it has conflicts
comment if you can

**Comment by KarenEfereyan** [comment]
I can.
I'm just out of laptop power now

**Comment by kofimokome** [comment]
wait., I will do it

**Comment by KarenEfereyan** [comment]
> wait., I will do it

Thank you very much

**Pull request merged**
