### PR TITLE
Task/refactor ux

### PR DESCRIPTION
**Pull request by orlawealth**
Refactored bsidebar and bheader UX
Ref
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnin

### CODE REVIEW

**Comment by kofimokome** [comment]
Please can you attach an image showing what you have done?

**Comment by orlawealth** [comment]
Screenshot (61)

**Comment by kofimokome** [comment]
@kadetXx pls review this UI

**Comment by kofimokome** [comment]
@kadetXx review fast. He's already having merge conflicts

**Comment by Jeremiahiro** [comment]
please resolve conflict

**Pull request closed without merging**
