### PR TITLE
worked on issue 81/redirect authenticated users from /backend, an error page to /backend/dashboard the dashboard

### PR DESCRIPTION
**Pull request by judeb21**

### CODE REVIEW

**Comment by kofimokome** [comment]
nothing has chaned

**Comment by kofimokome** [comment]
you still have 223 files changed

**Comment by kofimokome** [comment]
contact me on slack @kofimokome

**Comment by judeb21** [comment]
Yes @kofimokome there's another folder in the public directory called backend which is why laravel will throw a php error on that url because it looks in the public directory first. So I changed that directory and updated the everywhere the backend was referenced in the code then updated the route file

**Comment by kofimokome** [comment]
it looks like we'll instead change url to the backend.
let me contact the others

**Comment by Jeremiahiro** [comment]
so the issue has been fixed. Please confirm @kofimokome

**Comment by kofimokome** [comment]
that will be easier and very quick than to change the directory structure.
someone code not yet submitted may be using the structure

**Comment by judeb21** [comment]
No I did not change the structure, any one who's making a pr will have to pull from the repo and update their own repo

**Comment by kofimokome** [comment]
my issue is that you have 223 files changes. I don't time to review 223 files.
I'm closing the PR, your task remains but I will change the title and description

**Pull request closed without merging**
