### PR TITLE
"worked on issue 81/ redirect users from /backend, an error page to /backend/dashboard the dashboard"

### PR DESCRIPTION
**Pull request by judeb21**

### CODE REVIEW

**Comment by kofimokome** [comment]
hello, please @judeb21 
you can't have a pr of 222 files changed.

**Comment by Jeremiahiro** [comment]
please resolve conflict

Always pull before you push

**Comment by kofimokome** [comment]
Please you may need to redo you work. It will save us time fixing issues
1. pull from upstream develop the latest changes.
2. Push to origin develop
3. Add your changes
4. Commit
5. Push to develop
6. Create pull request

**Comment by kofimokome** [comment]
You shoud have only 1 file changed. If I'm not wrong

**Comment by kofimokome** [comment]
you are to work from develop not master.
contact me if you have any problem

**Pull request closed without merging**
