### PR TITLE
Created  Store UI  issue#42

### PR DESCRIPTION
**Pull request by SkyC0der**

### CODE REVIEW

**Comment by Jeremiahiro** [comment]
resolve conflict on routes/web.php

Always pull before you push

**Comment by kofimokome** [comment]
I will take care of the conflicts for web.php only

**Comment by kofimokome** [comment]
@SkyC0der ,
please add a description of what you did.
and also the edit page, the previous person said you are to finish it.
Can you finish it? please look at the issue description

**Comment by SkyC0der** [comment]
I created a page to view a specific store and finished the issues.

**Comment by kofimokome** [comment]
there is an edit page, you agreed you will finish the remaining pages.
Please can you add it

**Comment by SkyC0der** [comment]
i'm done

**Comment by kofimokome** [comment]
ok. I'm looking at it

**Comment by kofimokome** [comment]
@SkyC0der , I will take a long time to review your changes because
1. It has conflicts
2. some of your files without conflicts will override new changes
I will inform i need you to do some changes

**Comment by SkyC0der** [comment]
Done. Kindly review

**Comment by kofimokome** [comment]
waiting for the new pr

**Pull request closed without merging**
