### PR TITLE
Feat/implemented change language

### PR DESCRIPTION
**Pull request by Elvislogan**
change_lang

### CODE REVIEW

**Comment by kofimokome** [comment]
@Elvislogan I've 3 questions for you
1. Who assigned this task to you?
2. What is the issue number of github? every task has an issue number 
3. To add language switcher, you changed 458 files ? who will review 458 files

In short this request can't be merged because it is pointing to master instead of develop
when you answer the 3 questions I will decide to merge or not. for now, I'm closing the issue

**Comment by kofimokome** [comment]
There is even a language bar on the menu, this is just a duplicate, not approved, it's the icon after the search bar

**Comment by Elvislogan** [comment]
My Lead assigned the task to me. He told me that the page was approved and we that know how to use blade template in FE team were assigned some tasks. I was assigned this page. 
Sorry about trying to merge to master. I created another branch. I was trying to merge to develop branch. That was a mistake.

**Comment by Elvislogan** [comment]
It doesnt have an issue number on github. It was my lead that gave it to me today.
I really didnt touch those files. I just worked on my own. Then I added image to the images folder. That is all.

**Pull request closed without merging**
